// museair_test.cpp
// C++20-style MuseAir algorithm correctness test

#include <iostream>
#include <iomanip>
#include <vector>
#include <cstring>	// for strlen
#include <cstdint>
#include <utility>
#include <functional>

#include "MuseAir.hpp"

using seed_t = uint64_t;

//------------------------------------------------------------------------------
// Constants: 32-bit verification values generated by a trusted reference implementation
// (little-endian / big-endian, 64-bit / 128-bit)
inline constexpr uint32_t VERIFY64_LE_STANDARD = 0xF3F76DF0;
inline constexpr uint32_t VERIFY64_BE_STANDARD = 0x792FC8E0;
inline constexpr uint32_t VERIFY128_LE_STANDARD = 0xF42EF1BB;
inline constexpr uint32_t VERIFY128_BE_STANDARD = 0x59C90627;
inline constexpr uint32_t VERIFY64_LE_BFAST = 0xB970C19E;
inline constexpr uint32_t VERIFY64_BE_BFAST = 0xD629BA9A;
inline constexpr uint32_t VERIFY128_LE_BFAST = 0xA15818FE;
inline constexpr uint32_t VERIFY128_BE_BFAST = 0xC1CF9B1B;
inline constexpr uint32_t HASHBITS = 64;
inline constexpr uint32_t WIDEHASHBITS = 128;

//------------------------------------------------------------------------------
// HASH_INITIALIZE_SEED: for MuseAir, just return the seed directly
constexpr seed_t HASH_INITIALIZE_SEED( seed_t seed ) noexcept
{
	return seed;
}

//------------------------------------------------------------------------------
// ComputeVerify: hash prefixes of length 0..255 with 64-bit output, then hash
// the concatenation of those 256 outputs to produce a 32-bit verification value.
uint32_t ComputeVerify( const std::function<void( const void*, size_t, uint64_t, void* )>& hash_fn )
{
	constexpr size_t hashbytes = HASHBITS / 8;	// 8 bytes

	std::vector<uint8_t> key( 256, 0 );
	std::vector<uint8_t> hashes( 256 * hashbytes, 0 );
	std::vector<uint8_t> total( hashbytes, 0 );

	// Hash all prefixes of length 0..255
	for ( size_t i = 0; i < 256; ++i )
	{
		seed_t seed = HASH_INITIALIZE_SEED( static_cast<seed_t>( 256 - i ) );
		hash_fn( key.data(), i, seed, hashes.data() + i * hashbytes );
		key[ i ] = static_cast<uint8_t>( i );
	}

	// Hash the concatenation of those 256 intermediate outputs
	seed_t seed0 = HASH_INITIALIZE_SEED( 0 );
	hash_fn( hashes.data(), hashbytes * 256, seed0, total.data() );

	// Interpret total[0..3] as a 32-bit value according to native endianness
	uint32_t verification = 0;
	if constexpr ( std::endian::native == std::endian::little )
	{
		verification = static_cast<uint32_t>( read_u32<false>( total.data() ) );
	}
	else
	{
		verification = static_cast<uint32_t>( read_u32<true>( total.data() ) );
	}
	return verification;
}

//------------------------------------------------------------------------------
// ComputeVerify128: same as ComputeVerify, but each prefix hash is 128-bit
// (16 bytes), then the concatenation is hashed to produce a 32-bit value.
uint32_t ComputeVerify128( const std::function<void( const void*, size_t, uint64_t, void* )>& hash_fn )
{
	constexpr size_t hashbytes = WIDEHASHBITS / 8;	// 16 bytes

	std::vector<uint8_t> key( 256, 0 );
	std::vector<uint8_t> hashes( 256 * hashbytes, 0 );
	std::vector<uint8_t> total( hashbytes, 0 );

	// Hash all prefixes of length 0..255
	for ( size_t i = 0; i < 256; ++i )
	{
		seed_t seed = HASH_INITIALIZE_SEED( static_cast<seed_t>( 256 - i ) );
		hash_fn( key.data(), i, seed, hashes.data() + i * hashbytes );
		key[ i ] = static_cast<uint8_t>( i );
	}

	// Hash the concatenation of those 256 intermediate outputs
	seed_t seed0 = HASH_INITIALIZE_SEED( 0 );
	hash_fn( hashes.data(), hashbytes * 256, seed0, total.data() );

	// Interpret total[0..3] as a 32-bit value according to native endianness
	uint32_t verification = 0;
	if constexpr ( std::endian::native == std::endian::little )
	{
		verification = static_cast<uint32_t>( read_u32<false>( total.data() ) );
	}
	else
	{
		verification = static_cast<uint32_t>( read_u32<true>( total.data() ) );
	}
	return verification;
}

//------------------------------------------------------------------------------
// CompareVerify / CompareVerify128: compare computed verification value
// against the expected constant, printing an error if they differ.
bool CompareVerify( const std::function<void( const void*, size_t, uint64_t, void* )>& hash_fn, uint32_t expected_hash_value )
{
	uint32_t got = ComputeVerify( hash_fn );
	if ( got == expected_hash_value )
	{
		return true;
	}
	else
	{
		std::cout << std::hex << std::setfill( '0' );
		std::cout << "[ERROR] 64-bit verification failed: got = 0x" << std::setw( 8 ) << got << ", expected = 0x" << std::setw( 8 ) << expected_hash_value << std::endl;
		return false;
	}
}

bool CompareVerify128( const std::function<void( const void*, size_t, uint64_t, void* )>& hash_fn, uint32_t expected_hash_value )
{
	uint32_t got = ComputeVerify128( hash_fn );
	if ( got == expected_hash_value )
	{
		return true;
	}
	else
	{
		std::cout << std::hex << std::setfill( '0' );
		std::cout << "[ERROR] 128-bit verification failed: got = 0x" << std::setw( 8 ) << got << ", expected = 0x" << std::setw( 8 ) << expected_hash_value << std::endl;
		return false;
	}
}

//------------------------------------------------------------------------------
// print_hash_values: display sample 64-bit / 128-bit outputs for three strings,
// both standard and BlindFast-optimized implementations.
void print_hash_values()
{
	const uint8_t data1[] = "Hello, World!";
	const uint8_t data2[] = "The quick brown fox jumps over the lazy dog.";
	const uint8_t data3[] = "This is a very long string to test the performance of the hash function over a larger input.";

	const uint64_t seed = 0x123456789ABCDEF0ULL;
	constexpr bool is_big_endian = ( std::endian::native != std::endian::little );

	MuseAir<false> museAirStandard;	  // Standard implementation
	MuseAir<true>  museAirOptimized;  // BlindFast-optimized

	// ------- 64-bit hashes -------
	uint64_t hash1, hash2, hash3;
	museAirStandard.hash<is_big_endian>( data1, std::strlen( reinterpret_cast<const char*>( data1 ) ), seed, &hash1 );
	museAirStandard.hash<is_big_endian>( data2, std::strlen( reinterpret_cast<const char*>( data2 ) ), seed, &hash2 );
	museAirStandard.hash<is_big_endian>( data3, std::strlen( reinterpret_cast<const char*>( data3 ) ), seed, &hash3 );

	uint64_t hashOpt1, hashOpt2, hashOpt3;
	museAirOptimized.hash<is_big_endian>( data1, std::strlen( reinterpret_cast<const char*>( data1 ) ), seed, &hashOpt1 );
	museAirOptimized.hash<is_big_endian>( data2, std::strlen( reinterpret_cast<const char*>( data2 ) ), seed, &hashOpt2 );
	museAirOptimized.hash<is_big_endian>( data3, std::strlen( reinterpret_cast<const char*>( data3 ) ), seed, &hashOpt3 );

	std::cout << std::hex << std::setfill( '0' );
	std::cout << "=== 64-bit Hash ===\n";
	std::cout << "Standard:  data1 = 0x" << std::setw( 16 ) << hash1 << ", data2 = 0x" << std::setw( 16 ) << hash2 << ", data3 = 0x" << std::setw( 16 ) << hash3 << "\n";
	std::cout << "Optimized: data1 = 0x" << std::setw( 16 ) << hashOpt1 << ", data2 = 0x" << std::setw( 16 ) << hashOpt2 << ", data3 = 0x" << std::setw( 16 ) << hashOpt3 << "\n\n";

	// ------- 128-bit hashes -------
	uint8_t hash128_1[ 16 ], hash128_2[ 16 ], hash128_3[ 16 ];
	museAirStandard.hash_128<is_big_endian>( data1, std::strlen( reinterpret_cast<const char*>( data1 ) ), seed, hash128_1 );
	museAirStandard.hash_128<is_big_endian>( data2, std::strlen( reinterpret_cast<const char*>( data2 ) ), seed, hash128_2 );
	museAirStandard.hash_128<is_big_endian>( data3, std::strlen( reinterpret_cast<const char*>( data3 ) ), seed, hash128_3 );

	uint8_t hash128Opt1[ 16 ], hash128Opt2[ 16 ], hash128Opt3[ 16 ];
	museAirOptimized.hash_128<is_big_endian>( data1, std::strlen( reinterpret_cast<const char*>( data1 ) ), seed, hash128Opt1 );
	museAirOptimized.hash_128<is_big_endian>( data2, std::strlen( reinterpret_cast<const char*>( data2 ) ), seed, hash128Opt2 );
	museAirOptimized.hash_128<is_big_endian>( data3, std::strlen( reinterpret_cast<const char*>( data3 ) ), seed, hash128Opt3 );

	// Convert 8-byte chunks to uint64_t for printing
	auto to_u64 = []( const uint8_t* arr ) {
		uint64_t v = 0;
		if constexpr ( std::endian::native == std::endian::little )
		{
			std::memcpy( &v, arr, sizeof( uint64_t ) );
		}
		else
		{
			for ( size_t i = 0; i < 8; ++i )
			{
				v = ( v << 8 ) | arr[ i ];
			}
		}
		return v;
	};

	std::cout << "=== 128-bit Hash (printed as two 64-bit parts) ===\n";
	std::cout << "Standard:  data1 = 0x" << std::setw( 16 ) << to_u64( hash128_1 ) << to_u64( hash128_1 + 8 ) << ", data2 = 0x" << std::setw( 16 ) << to_u64( hash128_2 ) << to_u64( hash128_2 + 8 ) << ", data3 = 0x" << std::setw( 16 ) << to_u64( hash128_3 ) << to_u64( hash128_3 + 8 ) << "\n";

	std::cout << "Optimized: data1 = 0x" << std::setw( 16 ) << to_u64( hash128Opt1 ) << to_u64( hash128Opt1 + 8 ) << ", data2 = 0x" << std::setw( 16 ) << to_u64( hash128Opt2 ) << to_u64( hash128Opt2 + 8 ) << ", data3 = 0x" << std::setw( 16 ) << to_u64( hash128Opt3 ) << to_u64( hash128Opt3 + 8 ) << "\n\n";
}

//------------------------------------------------------------------------------
// main: print sample hashes and run verification (64-bit/128-bit, Standard/BlindFast)
int main()
{
	std::cout << ">>> MuseAir Algorithm Test (C++20)\n\n";
	print_hash_values();

	constexpr bool	   is_big_endian = ( std::endian::native != std::endian::little );
	MuseAir<false> museAirStandard;
	MuseAir<true>  museAirOptimized;

	// 64-bit Standard test
	std::cout << "--- 64-bit Standard verification ---\n";
	bool ok1 = CompareVerify( [ & ]( const void* data, size_t size, uint64_t seed, void* out ) { museAirStandard.hash<is_big_endian>( static_cast<const uint8_t*>( data ), size, seed, reinterpret_cast<uint64_t*>( out ) ); }, ( std::endian::native == std::endian::little ? VERIFY64_LE_STANDARD : VERIFY64_BE_STANDARD ) );
	if ( ok1 )
	{
		std::cout << "64-bit Standard: passed\n\n";
	}

	// 64-bit BlindFast (Optimized) test
	std::cout << "--- 64-bit BlindFast (Optimized) verification ---\n";
	bool ok3 = CompareVerify( [ & ]( const void* data, size_t size, uint64_t seed, void* out ) { museAirOptimized.hash<is_big_endian>( static_cast<const uint8_t*>( data ), size, seed, reinterpret_cast<uint64_t*>( out ) ); }, ( std::endian::native == std::endian::little ? VERIFY64_LE_BFAST : VERIFY64_BE_BFAST ) );
	if ( ok3 )
	{
		std::cout << "64-bit BlindFast: passed\n\n";
	}

	// 128-bit Standard test
	std::cout << "--- 128-bit Standard verification ---\n";
	bool ok2 = CompareVerify128( [ & ]( const void* data, size_t size, uint64_t seed, void* out ) { museAirStandard.hash_128<is_big_endian>( static_cast<const uint8_t*>( data ), size, seed, out ); }, ( std::endian::native == std::endian::little ? VERIFY128_LE_STANDARD : VERIFY128_BE_STANDARD ) );
	if ( ok2 )
	{
		std::cout << "128-bit Standard: passed\n\n";
	}

	// 128-bit BlindFast (Optimized) test
	std::cout << "--- 128-bit BlindFast (Optimized) verification ---\n";
	bool ok4 = CompareVerify128( [ & ]( const void* data, size_t size, uint64_t seed, void* out ) { museAirOptimized.hash_128<is_big_endian>( static_cast<const uint8_t*>( data ), size, seed, out ); }, ( std::endian::native == std::endian::little ? VERIFY128_LE_BFAST : VERIFY128_BE_BFAST ) );
	if ( ok4 )
	{
		std::cout << "128-bit BlindFast: passed\n\n";
	}

	// Final result
	if ( ok1 && ok2 && ok3 && ok4 )
	{
		std::cout << ">>> All MuseAir test vectors passed.\n";
		return 0;
	}
	else
	{
		std::cout << ">>> MuseAir test failed. See error messages above.\n";
		return 1;
	}
}
